version: 2.1

jobs:
  build-doc:
    resource_class: xlarge
    docker:
      - image:  circleci/python:3.7-stretch-node-browsers
    steps:
      - add_ssh_keys:
          fingerprints:
            - "dc:5f:39:48:00:b4:72:34:e1:d2:c4:e1:1f:d1:e2:ce" #plotlydocbot

      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - .venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: make html
          command: |
            . venv/bin/activate
            echo ${mapbox_token} > fsharp/.mapbox_token
            make html || make html
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              cd build/html
              git init
              git config user.name plotlydocbot
              git config user.email accounts@plot.ly
              git add *
              git commit -m "build of https://github.com/plotly/plotly.net-docs/commit/${CIRCLE_SHA1}"
              git push --force git@github.com:plotly/plotly.net-docs.git master:built
              rm -rf .git
              cd ../..
            fi
            tar -zcf build/html.tgz build/html
            rm -rf build/html
      - store_artifacts:
          path: build
          destination: build

workflows:
  build:
    jobs:
      - build-doc
