version: 2.1

jobs:
  build-doc:
    resource_class: xlarge
    docker:
      - image: circleci/python:3.7-stretch-node-browsers
    steps:
      - add_ssh_keys:
          fingerprints:
            - "dc:5f:39:48:00:b4:72:34:e1:d2:c4:e1:1f:d1:e2:ce" #plotlydocbot

      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dotnet sdk
          command: |
            wget https://packages.microsoft.com/config/ubuntu/21.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
            sudo dpkg -i packages-microsoft-prod.deb
            rm packages-microsoft-prod.deb
            sudo apt-get update
            sudo apt-get install -y apt-transport-https
            sudo apt-get update
            sudo apt-get install -y dotnet-sdk-5.0
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            jupyter kernelspec list
      - run:
          name: install dot net interactive
          command: |
            . venv/bin/activate
            dotnet tool restore
            dotnet dotnet-interactive jupyter install
            jupyter kernelspec list

      - save_cache:
          paths:
            - .venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: make html
          command: |
            . venv/bin/activate
            echo ${mapbox_token} > fsharp/.mapbox_token
            echo ${mapbox_token} > csharp/.mapbox_token
            make
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              cd build
              git init
              git config user.name plotlydocbot
              git config user.email accounts@plot.ly
              git add csharp/*.html
              git add fsharp/*.html
              git commit -m "build of https://github.com/plotly/plotly.net-docs/commit/${CIRCLE_SHA1}"
              git push --force git@github.com:plotly/plotly.net-docs.git master:built
              rm -rf .git
              cd ../..
            fi
            tar -zcf build.tgz build
            rm -rf build
      - store_artifacts:
          path: build
          destination: build

      - run:
          name: trigger doc build
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              git clone --depth=1 https://github.com/plotly/graphing-library-docs.git
              cd graphing-library-docs
              git config user.name plotlydocbot
              git config user.email accounts@plot.ly
              git commit --allow-empty -m "deploying https://github.com/plotly/plotly.net-docs/commit/${CIRCLE_SHA1}"
              git push
              cd ..
              rm -rf graphing-library-docs
            fi
workflows:
  build:
    jobs:
      - build-doc
